### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by UnknownNull** [funniray/waterdog-litebans#3]

**Comment by funniray** [comment]
Hey there,

What needs updating? Does it not work on newer versions of WaterdogPE -- if so, then what error messages do you get?

**Comment by UnknownNull** [comment]
![image](https://user-images.githubusercontent.com/91208232/227590408-f215ac55-e64e-4605-90e8-65ba4a284a44.png)

**Comment by funniray** [comment]
Is this with waterdogPE 2.0.0 or 1.2.4?

**Comment by UnknownNull** [comment]
waterdogPE 1.2.4

**Comment by funniray** [comment]
Try to download the artifact called `Package` on this page and see if that makes the error go away
https://github.com/funniray/waterdog-litebans/actions/runs/4513734604

**Comment by UnknownNull** [comment]
Apparently there is no problem. But in the future I will do more tests and if there is a bug I will report it.
Thank You

**Comment by funniray** [comment]
I'll make a better fix in a

**Comment by UnknownNull** [comment]
update?

**Comment by funniray** [comment]
> update?

Should've just updated it, hope it fixes the issue? Next time, be more specific, use more words than one. If you make another vague comment/issue in the future, I will ignore it.

Please also open new issues instead of commenting on old ones.
